const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#10A37F",
    background: "#F7F7F8",
    foreground: "#0a0a0a",
    card: "#FFFFFF",
    cardForeground: "#0a0a0a",
    primary: "#10A37F",
    primaryForeground: "#FFFFFF",
    secondary: "#F0F0F0",
    secondaryForeground: "#1a1a1a",
    muted: "#EBEBEB",
    mutedForeground: "#6B6B6B",
    accent: "#E8F5F1",
    accentForeground: "#0B7A5E",
    destructive: "#E53935",
    destructiveForeground: "#FFFFFF",
    border: "#E5E5E5",
    input: "#E5E5E5",
    userBubble: "#10A37F",
    userBubbleText: "#FFFFFF",
    assistantBubble: "#FFFFFF",
    assistantBubbleText: "#0a0a0a",
    thinkingBg: "#F0F9F6",
    thinkingBorder: "#10A37F",
    thinkingText: "#0B7A5E",
    inputBg: "#FFFFFF",
    headerBg: "#FFFFFF",
  },
  dark: {
    text: "#ECECEC",
    tint: "#10A37F",
    background: "#0D0D0D",
    foreground: "#ECECEC",
    card: "#1A1A1A",
    cardForeground: "#ECECEC",
    primary: "#10A37F",
    primaryForeground: "#FFFFFF",
    secondary: "#212121",
    secondaryForeground: "#ECECEC",
    muted: "#2A2A2A",
    mutedForeground: "#8E8EA0",
    accent: "#0D2B24",
    accentForeground: "#10A37F",
    destructive: "#CF4E4E",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2A",
    input: "#1A1A1A",
    userBubble: "#10A37F",
    userBubbleText: "#FFFFFF",
    assistantBubble: "#1E1E1E",
    assistantBubbleText: "#ECECEC",
    thinkingBg: "#0D1F1A",
    thinkingBorder: "#1A5040",
    thinkingText: "#6ECAAD",
    inputBg: "#1A1A1A",
    headerBg: "#0D0D0D",
  },
  radius: 12,
};

export default colors;
